export default Object.freeze({
    // Misc
    DEFAULT_PORT: 8080,
    ADMIN: false,

    // HTTP
    HTTP_NOT_FOUND: 404,
    HTTP_SERVER_ERROR: 500,
    HTTP_CREATED: 201,
    HTTP_NOT_AUTHORIZED: 403,
    HTTP_BAD_REQUEST: 400,

    // Custom Error Codes
    NOT_AUTH_ERRCODE: -1,
    ROUTE_NOT_FOUND_ERRCODE: -2,
    INVALID_ID_ERRCODE: -3,
    PROD_NOT_FOUND_ERRCODE: -4,
    CHRT_NOT_FOUND_ERRCODE: -5,
})